# Default values for go-vue-websockets.

replicaCount: 1

image:
  repository: cvasquez/go-vue-websockets
  tag: latest
  pullPolicy: Always

service:
  name: go-vue-websockets
  type: NodePort
  externalPort: 8080
  internalPort: 8080
  port: 8080

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3                                                                                                                                                                                                                                                                                                        
readinessProbe:
  enabled: true
  path: /ready
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/add-base-url: 'true'

  path: /websocket-echo/?(.*)
  hosts:
    - demos.cvasquez.dev
  tls: 
    - secretName: chart-example-tls
      hosts:
        - demos.cvasquez.dev

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
